parameters:
#    rto_core.example.class: Rto\CoreBundle\Example

services:
#    rto_core.example:
#        class: %rto_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
