parameters:
#    rto_user.example.class: Rto\UserBundle\Example

services:
#    rto_user.example:
#        class: %rto_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
