parameters:
#    rto_admin.example.class: Rto\AdminBundle\Example

services:
#    rto_admin.example:
#        class: %rto_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
