parameters:
#    rto_operations.example.class: Rto\OperationsBundle\Example

services:
#    rto_operations.example:
#        class: %rto_operations.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
